### PR TITLE
add media contents downloader

### PR DESCRIPTION
**Pull request by qytz**

### CODE REVIEW

**Comment by geekan** [comment]
Looks good.
Can it deal with pages those need to be rendered?

**Comment by qytz** [comment]
Yes, I think，I tested with changba's music file.

**Comment by geekan** [comment]
I mean some pages need to be rendered (run JavaScript) and then it will extract the correct data.
I've checked the code of the project, but I haven't found anything about it.

**Comment by smnslwl** [comment]
I've never used it, but this seems like a command-line utility built using Python, and not a library that you can use in Python programs. Nifty tool, but does not belong here.

**Comment by qytz** [comment]
It cannot deal with pages those need to be rendered, there is also a GUI version which listed sites supported in details: https://github.com/ingbyr/GUI-YouGet
I think it is a library which also offers a simple client command.

**Comment by geekan** [comment]
@smnslwl We have a Utilities section.
@qytz LGTM. Merge now.

**Pull request merged**
